#!/bin/bash
echo "Building distribution"
let minor=$(cat MINOR_VERSION)
let minor=minor+1
echo $minor > MINOR_VERSION
git commit -a -m "Updated minor version"
./stamp
zip ../np.zip *
cp ../np.zip ../versions/np$(cat MAJOR_VERSION).$(cat MINOR_VERSION).zip
git commit -a -m "Stamped with $(cat MAJOR_VERSION).$(cat MINOR_VERSION)"
echo "Upload np.zip to the chrome store, and push git repo."
echo "Then git revert the numbering."
